apiVersion: v1
kind: Service
metadata:
  name: pathaks-hostel-service
spec:
  # This tells AWS to give you a Public URL
  type: ClusterIP
  selector:
    # This MUST match your Deployment label
    app: pathaks-hostel
  ports:
    - protocol: TCP
      # This is the port you will put in your browser
      port: 80
      # This is the port your app.js is listening on
      targetPort: 5000
