replicaCount: 1

image:
  repository: pathaks-hostel  # ⚠️ Change this to your Docker Hub ID (e.g., atrayee31/pathaks-hostel)
  pullPolicy: IfNotPresent
  tag: "21298775517"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true   # ⚠️ Must be true for AWS to work
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: null  # null allows the AWS LoadBalancer URL to work
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80